### Creates the movies in this list
POST http://localhost:8080/api/movies/all
Content-Type: application/json

[
  {
    "title": "Gladiator",
    "launchDate": "2000-01-05",
    "rating": 8.5,
    "revenue": 451683599
  },
  {
    "title": "Inception",
    "launchDate": "2010-07-16",
    "rating": 8.8,
    "revenue": 825786894
  }
]



### Creates a new movie
POST http://localhost:8080/api/movies
Content-Type: application/json

{
    "title" : "Forrest Gump",
    "launchDate" : "1994-10-28",
    "rating" : 8.0,
    "revenue": 679835137
}



###Returns the movie with id = 2
GET http://localhost:8080/api/movies/2



###Returns all movies
GET http://localhost:8080/api/movies/all



###Returns all movies with launchDate = "1994-10-28"
GET http://localhost:8080/api/movies/launchDate/1994-10-28



### Updates movie with id = 1 to a new movie
PUT http://localhost:8080/api/movies/1
Content-Type: application/json

{
    "title": "Fight Club",
    "launchDate": "1999-11-12",
    "rating": 8.8,
    "revenue": 100900000
}


###Returns the movie with id = 1
GET http://localhost:8080/api/movies/1


###Deletes the movie with id = 1
DELETE http://localhost:8080/api/movies/1


###Deletes all movies
DELETE http://localhost:8080/api/movies/all

###Exceptions

###Tries to return the movie with id = 1 after previously deleting all the movies in the database
GET http://localhost:8080/api/movies/1


###Tries to updates the movie with id = 2 to a new movie after previously deleting all the movies in the database
PUT http://localhost:8080/api/movies/1
Content-Type: application/json

{
    "title": "Fight Club",
    "launchDate": "1999-11-12",
    "rating": 8.8,
    "revenue": 100900000
}



###Tries to create a movie with a rating < 0
POST http://localhost:8080/api/movies
Content-Type: application/json

{
    "title": "Fight Club",
    "launchDate": "1999-11-12",
    "rating": -5.2,
    "revenue": 100900000
}


###Tries to create a movie with a rating > 10
POST http://localhost:8080/api/movies
Content-Type: application/json

{
    "title": "Fight Club",
    "launchDate": "1999-11-12",
    "rating": 15.0,
    "revenue": 100900000
}


###Tries to create a movie with no tittle
POST http://localhost:8080/api/movies
Content-Type: application/json

{
    "title": "",
    "launchDate": "1999-11-12",
    "rating": 8.8,
    "revenue": 100900000
}



###Tries to create a movie with no tittle
POST http://localhost:8080/api/movies
Content-Type: application/json

{
    "title": null,
    "launchDate": "1999-11-12",
    "rating": 8.8,
    "revenue": 100900000
}



###Tries to create a movie with no launchDate
POST http://localhost:8080/api/movies
Content-Type: application/json

{
    "title": "Fight Club",
    "launchDate": "",
    "rating": 8.8,
    "revenue": 100900000
}

###Tries to create a movie with invalid launchDate
POST http://localhost:8080/api/movies
Content-Type: application/json

{
    "title": "Fight Club",
    "launchDate": "1999-12-1919191",
    "rating": 8.8,
    "revenue": 100900000
}



###Tries to create a movie with invalid launchDate
POST http://localhost:8080/api/movies
Content-Type: application/json

{
    "title": "Fight Club",
    "launchDate": "1999-12",
    "rating": 8.8,
    "revenue": 100900000
}


###Tries to create a movie with invalid launchDate
POST http://localhost:8080/api/movies
Content-Type: application/json

{
    "title": "Fight Club",
    "launchDate": "12-1919191",
    "rating": 8.8,
    "revenue": 100900000
}


###Tries to create a movie with invalid launchDate
POST http://localhost:8080/api/movies
Content-Type: application/json

{
    "title": "Fight Club",
    "launchDate": "1999919191",
    "rating": 8.8,
    "revenue": 100900000
}



###Tries to create a movie with invalid launchDate (future date)
POST http://localhost:8080/api/movies
Content-Type: application/json

{
    "title": "Fight Club",
    "launchDate": "2030-11-10",
    "rating": 8.8,
    "revenue": 100900000
}



###Tries to create a movie with no rating
POST http://localhost:8080/api/movies
Content-Type: application/json

{
  "title": "Fight Club",
  "launchDate": "1999-11-12",
  "rating": null,
  "revenue": 100900000
}


###Tries to create a movie with no revenue
POST http://localhost:8080/api/movies
Content-Type: application/json

{
    "title": "Fight Club",
    "launchDate": "1999-11-12",
    "rating": 8.8,
    "revenue": null
}